### ISSUE TITLE
function create images fails when using images_to_movies

### ISSUE THREAD

**Issue by firstkingofrome** [shaharkadmiel/pySW4#15]
Hello the function create_images has some problems (I am running on python 2.7.14:
in image.py
1. On line 200 glob isnt invoked correctly, should be  all_files = glob.glob(os.path.join(folder, "*.sw4img"))
2.  Similarly on line 200 warn(msg) needs to be warnings.warn(msg)
3.  patch data needs to be accessed, not the patch object
            global_min = min(global_min, patch.data.min())
            global_max = max(global_max, patch.data.max())

**Comment by shaharkadmiel** [comment]
There where some bugs indeed. Everything seems to work now. Install from master and let me know if problems persist.
