### ISSUE TITLE
Problem with patches 

### ISSUE THREAD

**Issue by Anupam2372** [shaharkadmiel/pySW4#18]
The bugs arise at the patches, like, for a small section of code-

f = '../sw4-v1.1/examples/rfile/results/berkeley.cycle=00000.x=2500.p.sw4img'
image = sw4.read_image(f, input_)

print image
for patch in image.patches:
    print patch

print image.curvilinear_grid_patch
   
image.patches[1].plot()
image.patches[0].plot()

**Comment by shaharkadmiel** [comment]
By the looks of it you are using a very old version of `pySW4`.

please clone the master branch:

```shell
$ git clone git@github.com:shaharkadmiel/pySW4.git
```

and install locally with pip:

```shell
$ cd pySW4
$ pip install .
```

 You might have to first uninstall `pySW4`. That may differ depending on how you initially installed it.
