### ISSUE TITLE
cannot import Inventory

### ISSUE THREAD

**Issue by shaharkadmiel** [shaharkadmiel/pySW4#3]
```python
pySW4/core/scripts/plotting.py", line 8, in <module>
    from obspy import read, Stream, read_inventory, Inventory
ImportError: cannot import name Inventory
```

@megies, I believe `Inventory` is not imported to the obspy namespace so at the moment i am adding `from obspy.station.inventory import Inventory
` to the imports section in `pySW4.core.scripts.plotting`

**Comment by megies** [comment]
Yes, probably `Inventory` is not in top level namespace in obspy `0.10.2`.. so this is the right thing to do (for now, this will change in the next major release).
